[[constraint]]
  branch = "master"
  name = "github.com/crushedpixel/cement"

[[constraint]]
  branch = "master"
  name = "github.com/crushedpixel/ferry"

[[constraint]]
  branch = "master"
  name = "github.com/crushedpixel/http_bridge"

[[constraint]]
  branch = "master"
  name = "github.com/desertbit/glue"

[prune]
  go-tests = true
  unused-packages = true
